author: Thinkan # 作者
description: Thinkan's blog
keyword: Thinkan, Android
favicon: /css/images/logo.png
google_site: 6jej_kTWDvGbTKnNXUPgwTNmtrfBDpip0z8t-ARzGzw
baidu_site: xId0ZGtc4p
excerpt_link: 全文

menu:
 首页: /
 标签: /tags/
 归档: /archives/
# Projects: /project/
 关于: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

#comment: gitment

# gitment config
#gitment_owner: Thinkan
#gitment_repo: Thinkan.github.io
#gitment_oauth_id: 0f87e490e00ee3fd87ef
#gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 116b4e912e38ec4afa8445b91230a3d7

# disqus config
disqus_shortname: 

about: 
  banner: /image/about.jpg
  avatar: /css/images/logo.png
  description: 有些事情如果不在合适的年纪去做，就永远都不会做了。
#  weibo_username: Thinkan
#  twitter_username: Thinkan
  github_username: Thinkan
#  zhihu_username: Thinkan
#  douban_username: Thinkan
#  linkedin_username:
  email_username: thinkan@126.com

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
